apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-test-deployment
  labels:
    app: frontend-app
spec:
  selector:
    matchLabels:
      project: react
  template:
    metadata:
      labels:
        project: react
    spec:
      containers:
        - name: react-app
          image: spisarevskiy/react-test-app:latest
          ports:
            - containerPort: 80

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: cluster-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1
    kind: Deployment
    name: frontend-test-deployment
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 70

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-test-service
  labels:
    env: prod
    owner: SergeyPisarevskiy
spec:
  selector:
    project: react    # Selecting Pods with thoose labels
  ports:
    - name: app-listener
      protocol: TCP
      port: 80         # Port on Load Balancer
      targetPort: 80   # Port on Pod
  type: LoadBalancer